micronaut:
  application:
    name: pizzaService
camunda:
  locations:
    - classpath:.
    - classpath:./BPMN
  admin-user:
    id: admin
    password: admin
  webapps:
    enabled: true
  rest:
    enabled: true
  filter:
    create: Show all
  generic-properties:
    properties:
      initialize-telemetry: true
